# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Simple.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.toolButtonStart = QtWidgets.QToolButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButtonStart.sizePolicy().hasHeightForWidth())
        self.toolButtonStart.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("start.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.toolButtonStart.setIcon(icon)
        self.toolButtonStart.setIconSize(QtCore.QSize(30, 30))
        self.toolButtonStart.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButtonStart.setObjectName("toolButtonStart")
        self.horizontalLayout.addWidget(self.toolButtonStart)
        self.toolButtonPrev = QtWidgets.QToolButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButtonPrev.sizePolicy().hasHeightForWidth())
        self.toolButtonPrev.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonPrev.setIcon(icon1)
        self.toolButtonPrev.setIconSize(QtCore.QSize(30, 30))
        self.toolButtonPrev.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButtonPrev.setObjectName("toolButtonPrev")
        self.horizontalLayout.addWidget(self.toolButtonPrev)
        self.toolButtonNext = QtWidgets.QToolButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButtonNext.sizePolicy().hasHeightForWidth())
        self.toolButtonNext.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonNext.setIcon(icon2)
        self.toolButtonNext.setIconSize(QtCore.QSize(30, 30))
        self.toolButtonNext.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButtonNext.setObjectName("toolButtonNext")
        self.horizontalLayout.addWidget(self.toolButtonNext)
        self.toolButtonPause = QtWidgets.QToolButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButtonPause.sizePolicy().hasHeightForWidth())
        self.toolButtonPause.setSizePolicy(sizePolicy)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.toolButtonPause.setIcon(icon3)
        self.toolButtonPause.setIconSize(QtCore.QSize(30, 30))
        self.toolButtonPause.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButtonPause.setObjectName("toolButtonPause")
        self.horizontalLayout.addWidget(self.toolButtonPause)
        self.toolButtonStop = QtWidgets.QToolButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButtonStop.sizePolicy().hasHeightForWidth())
        self.toolButtonStop.setSizePolicy(sizePolicy)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.toolButtonStop.setIcon(icon4)
        self.toolButtonStop.setIconSize(QtCore.QSize(30, 30))
        self.toolButtonStop.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButtonStop.setObjectName("toolButtonStop")
        self.horizontalLayout.addWidget(self.toolButtonStop)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.graphicsViewAction = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsViewAction.setObjectName("graphicsViewAction")
        self.verticalLayout.addWidget(self.graphicsViewAction)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.tableViewAction = QtWidgets.QTableView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableViewAction.sizePolicy().hasHeightForWidth())
        self.tableViewAction.setSizePolicy(sizePolicy)
        self.tableViewAction.setObjectName("tableViewAction")
        self.verticalLayout.addWidget(self.tableViewAction)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Robot Sequence"))
        self.toolButtonStart.setText(_translate("mainWindow", "Start"))
        self.toolButtonPrev.setText(_translate("mainWindow", "Previous"))
        self.toolButtonNext.setText(_translate("mainWindow", "Next"))
        self.toolButtonPause.setText(_translate("mainWindow", "Pause"))
        self.toolButtonStop.setText(_translate("mainWindow", "Stop"))
        self.label.setText(_translate("mainWindow", "Auto Actions of Robot by machine learning"))

